name: build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        release:
          - openwrt-25.12
        arch:
          - mediatek-filogic
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          PACKAGES: mollysocket
          #NO_REFRESH_CHECK: true
          NO_SHFMT_CHECK: true
          #NO_DEFAULT_FEEDS: true
          #EXTRA_FEEDS: >-
          #  src-git|packages|https://github.com/openwrt/packages.git;${{ matrix.release }}
          #  src-git|luci|https://github.com/openwrt/luci.git;${{ matrix.release }}
          #  src-git|routing|https://github.com/openwrt/routing.git;${{ matrix.release }}
          #  src-git|telephony|https://github.com/openwrt/telephony.git;${{ matrix.release }}
          V: sc

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: mollysocket-${{ matrix.arch }}_${{ matrix.release }}
          path: bin/packages/**/mollysocket*.apk
